In [20]:
import pandas as pd

# Load the stroke data
data_path = 'stroke.csv'
stroke_data = pd.read_csv(data_path)

# Display the first few rows of the data to verify it has been loaded correctly
stroke_data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [21]:
# Check for missing values
stroke_data.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [22]:
# Fill missing values in the bmi column with the mean of the column
stroke_data['bmi'].fillna(stroke_data['bmi'].mean(), inplace=True)

# Verify that there are no more missing values
stroke_data.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [23]:
# Perform one-hot encoding on the categorical variables
stroke_data_encoded = pd.get_dummies(stroke_data, columns=['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status'], drop_first=True)

# Display the first few rows of the encoded data to verify
stroke_data_encoded.head()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Male,gender_Other,ever_married_Yes,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,9046,67.0,0,1,228.69,36.600000,1,True,False,True,False,True,False,False,True,True,False,False
1,51676,61.0,0,0,202.21,28.893237,1,False,False,True,False,False,True,False,False,False,True,False
2,31112,80.0,0,1,105.92,32.500000,1,True,False,True,False,True,False,False,False,False,True,False
3,60182,49.0,0,0,171.23,34.400000,1,False,False,True,False,True,False,False,True,False,False,True
4,1665,79.0,1,0,174.12,24.000000,1,False,False,True,False,False,True,False,False,False,True,False

In [24]:
from sklearn.model_selection import train_test_split

# Split the data into features (X) and target (y)
X = stroke_data_encoded.drop(columns=[ 'stroke'])
y = stroke_data_encoded['stroke']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shape of the training and testing sets
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4088, 17), (1022, 17), (4088,), (1022,))

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Train a Logistic Regression model
log_reg = LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train, y_train)

# Make predictions on the test set
y_pred_log_reg = log_reg.predict(X_test)

# Evaluate the model
print("Logistic Regression Classification Report:\n")
print(classification_report(y_test, y_pred_log_reg))

Logistic Regression Classification Report:

              precision    recall  f1-score   support

           0       0.94      1.00      0.97       960
           1       0.00      0.00      0.00        62

    accuracy                           0.94      1022
   macro avg       0.47      0.50      0.48      1022
weighted avg       0.88      0.94      0.91      1022

In [26]:
from sklearn.tree import DecisionTreeClassifier

# Train a Decision Tree Classifier
dt_clf = DecisionTreeClassifier(random_state=42)
dt_clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred_dt = dt_clf.predict(X_test)

# Evaluate the model
print("Decision Tree Classifier Classification Report:\n")
print(classification_report(y_test, y_pred_dt))

Decision Tree Classifier Classification Report:

              precision    recall  f1-score   support

           0       0.94      0.97      0.96       960
           1       0.18      0.11      0.14        62

    accuracy                           0.91      1022
   macro avg       0.56      0.54      0.55      1022
weighted avg       0.90      0.91      0.91      1022

In [8]:
from sklearn.ensemble import RandomForestClassifier

# Train a Random Forest Classifier
rf_clf = RandomForestClassifier(random_state=42)
rf_clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = rf_clf.predict(X_test)

# Evaluate the model
print("Random Forest Classifier Classification Report:\n")
print(classification_report(y_test, y_pred_rf))

Random Forest Classifier Classification Report:

              precision    recall  f1-score   support

           0       0.94      1.00      0.97       960
           1       0.00      0.00      0.00        62

    accuracy                           0.94      1022
   macro avg       0.47      0.50      0.48      1022
weighted avg       0.88      0.94      0.91      1022

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [28]:
from imblearn.over_sampling import SMOTE

# Apply SMOTE to the training data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Train and evaluate Logistic Regression with SMOTE
log_reg_smote = LogisticRegression(max_iter=1000, random_state=42)
log_reg_smote.fit(X_train_smote, y_train_smote)
y_pred_log_reg_smote = log_reg_smote.predict(X_test)

print("Logistic Regression with SMOTE Classification Report:\n")
print(classification_report(y_test, y_pred_log_reg_smote))

# Train and evaluate Decision Tree Classifier with SMOTE
dt_clf_smote = DecisionTreeClassifier(random_state=42)
dt_clf_smote.fit(X_train_smote, y_train_smote)
y_pred_dt_smote = dt_clf_smote.predict(X_test)

print("\nDecision Tree Classifier with SMOTE Classification Report:\n")
print(classification_report(y_test, y_pred_dt_smote))

# Train and evaluate Random Forest Classifier with SMOTE
rf_clf_smote = RandomForestClassifier(random_state=42)
rf_clf_smote.fit(X_train_smote, y_train_smote)
y_pred_rf_smote = rf_clf_smote.predict(X_test)

print("\nRandom Forest Classifier with SMOTE Classification Report:\n")
print(classification_report(y_test, y_pred_rf_smote))

Logistic Regression with SMOTE Classification Report:

              precision    recall  f1-score   support

           0       0.98      0.69      0.81       960
           1       0.14      0.77      0.24        62

    accuracy                           0.70      1022
   macro avg       0.56      0.73      0.53      1022
weighted avg       0.93      0.70      0.78      1022


Decision Tree Classifier with SMOTE Classification Report:

              precision    recall  f1-score   support

           0       0.95      0.91      0.93       960
           1       0.14      0.24      0.18        62

    accuracy                           0.87      1022
   macro avg       0.55      0.57      0.55      1022
weighted avg       0.90      0.87      0.88      1022

NameError: name 'RandomForestClassifier' is not defined